project:
  type: book

book:
  title: "Field Methods in Plant Photobiology"
  subtitle: "From Principles to Practice"
  author: "Pedro J. Aphalo, Wolfgang Bilger, Marcel A. K. Jansen, Eva Rosenqvist (eds.)"
  date: "2024-07-15"
  date-format: iso
  chapters:
    - index.qmd
    - preface.qmd
    - contents.qmd
    - introduction.qmd
    - radiation-and-optics.qmd
    - light-environment.qmd
    - references.qmd

bibliography: 
  - handbook-1ed.bib
  - introduction.bib
  - radiation-and-optics.bib
  - light-environment.bib
  - references-from-1ed.bib

format:
  html:
    theme: cosmo
    resource-path: 
      - ./images
      - ./figures
  pdf:
    documentclass: scrreprt
    resource-path: 
      - ./images
      - ./figures

editor: source

