project:
  type: book

book:
  title: "Field Methods in Plant Photobiology"
  subtitle: "From Principles to Practice"
  author: 
    - name: Pedro J. Aphalo
      orcid: 0000-0003-3385-972X
      email: pedro.aphalo@helsinki.fi
      affiliation: University of Helsinki
    - name: Wolfgang Bilger
      orcid: 0000-0001-7800-4210
      affiliation: Christian-Albrechts-Universität zu Kiel
    - name: Marcel A. K. Jansen
      orcid: 0000-0003-2014-5859
      affiliation: University College Cork
    - name: Eva Rosenqvist
      orcid: 0000-0001-9288-6248
      affiliation: University of Copenhagen
  contributor: "Pedro J. Aphalo, Andreas Albert, Lars Olof Björn, Andy R. McLeod, T. Matthew Robson,  Eva Rosenqvist"
  license: "CC BY-SA"
  date: "2024-07-15"
  date-format: iso
  chapters:
    - index.qmd
    
    - preface-1ed.qmd
    - preface.qmd
    - contents.qmd
    - abbreviations.qmd
    
    - part: Basics
      chapters:
        - introduction.qmd
        - radiation.qmd
        - optics.qmd
        - light-environment-terrestrial.qmd
        - light-environment-aquatic.qmd
        
    - part: Measurements
      chapters:
        - quantifying-radiation.qmd
        - leaf-optics.qmd
        - quantifying-responses.qmd
        - imaging.qmd
      
    - part: Design and planning
      chapters:
        - design-of-experiments.qmd
        - reproducibility.qmd
        
    - part: Realization and treatments
      chapters:
        - manipulating-radiation.qmd
        - plant-cultivation.qmd
      
    - references.qmd
  page-footer:
    right:
      - text: "&copy; 2012-2024 COST office and authors"
    left:
      - text: "Uv4Plants Association"
        href: https://www.uv4plants.org
  page-navigation: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**EARLY DRAFT:**"
    type: primary
    position: below-navbar
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true
  draft-mode: visible
  
bibliography:
  - handbook-1ed.bib
  - introduction.bib
  - radiation-and-optics.bib
  - light-environment.bib
  - statistics-reproducibility.bib
  - references-from-1ed.bib

format:
  html:
    theme: cosmo
    resource-path: 
      - ./images
      - ./figures
    search: true

  pdf:
    documentclass: scrreprt

editor: source
freeze: false

