---
title: "Imaging in UV, VIS and NIR radiation"
subtitle: "Methods and equipment"
author: "Pedro J. Aphalo, (Eva Rosenqvist), (Lasse Ylianttila)"
---

## Cameras

Most photography cameras aim at producing images that reproduce a scene as seen by humans. When producing colour images image sensors with three channels are used, with sensors with designed to mimic the spectral sensitivity of the three photoreceptors participating in human day-time vision. This also applies to colour films (and video, TV and colour printing). In the case of greyscale (= black and white, BW) photographic films and very few digital cameras the images produced aim at reproducing the brightness of an scene as seen by humans. In other words, photograpoc cameras are designed to work as proxies for human vision.

Cameras used in industrial automation (= "machine vision"), astronomy, microscopy, etc., frequently use the same of similar image sensors as photography cameras, but exceptions are more common. Momochrome cameras are abundant and NIR cameras rather abundant. Cameras for UV are available and exceptionally, cameras for UV-B and even UV-C. Thermal IR cameras, designed for temperature measurements are monochromatic and sensitive to radiation in the range $8\,\mu m$ to $14\,\mu m$ (for $-20^\circ\mathrm{C}$ to $1500^\circ\mathrm{C}$), $0.85\,\mu m$ to $1.1\,\mu m$ (for $450^\circ\mathrm{C}$ to $1800^\circ\mathrm{C}$, used for hot metal), and other variants.

Spectral cameras cover the VIS wavelength range with more than three "colour" channels. Hyperspectral cameras frequently cover a wider range of wavelengths and have high wavelength resolution, i.e., they measure a spectrum for each pixel in the acquired image. Most of the these cameras cover the VIS and/or NIR but not UV.

With static subjects it is possible to acquire the images for the different
wavelengths sequentially, even using black and white film or a monochromatic
digital camera. This is how some early colour photography techniques
were implemented using band-pass filters under sunlight or white light, and persisted mainly in reproduction work. Alternatively, in a darkened space,
light of different colour can be used for illumination to the same effect.

### Head-less cameras

Machine vision cameras used in industrial automation and cameras for microscopy and other scientific uses are optionally available without NIR blocking filters and recently Sony has announced an image sensor with sensitivity in the short UV. In addition to colour cameras, monochrome cameras are also available. Some of the cameras used for machine vision and research are capable of capturing images at a very fast rate. Other cameras, such as those used for astronomy, have low noise sensors, sometimes with active cooling, that can work with very low light levels. Many, but not all, of these cameras are expensive and ment to be used thetered to a computer or at least with a separate screen, lacking a built-in screen and having few built-in controls. Some are intended to be mounted at a fixed position or at least on a tripod while others are suityable for use in drones. In most cases these cameras produce live images, can be fully controlled remotely either by wire (ethernet or USB) or wirelessly (Wifi).

There are also cheap cameras sold for use with microcontrollers or single-board computers like the Raspberry Pi and Arduino that are available in two versions with and without a NIR-blocking filter. The cameras use sensors similar or even identical to those in smart phones. These cameras can be used only thetered to one of these boards. The connection to the boards is by wire and only at very short distances. Remote and local access is through the controller board. More recently very small boards based on ESP32 microcontrollers have become available with built-in cameras and able to connect through wireless prococols like Wifi, Bluetooth and Matter. The image sensors used in these cheap cameras even if in same cases have high pixels resolution are small, and rarely good for use in low light conditions.

### Digital photography cameras

The cameras sold for photography are self contained: all controls, viewfinder and/or live-view screen, image review and image data storage all take place in-camera, and cameras are battery powered. Most cameras for ordinary photography are designed for imaging reflected visible light. In a few cases, manufacturers have offered versions of these cameras for use in forensics, with extended wavelength range. The sensors used are natively sensitive to shorter and longer wavelengths but optical filters attached to them limit the wavelngth range. Depending on the camera the shortest wavelengths that are detected vary between $380 nm$ and $410 nm$, and the longest ones between $680 nm$ and $730 nm$. The filters used are usually absoptive ionic and the cut-in and cut-off, specialy at the NIR end, are gradual, i.e., it is possible to use a $720 nm$ long-pass filter in most cameras but only by increasing exposure by orders of magnitude. Most of these cameras have colour sensors with red, green and blue filters on individual pixels. Currently, there are three monochromatic (or greyscale) system cameras in this group: Leica xxx, Pentax xxxx and xxxx.

It is possible to _convert_ cameras to _"full spectrum"_ (meaning the native sensitivity of the sensor) or alternatively a to especific range of wavelengths by replacing the filter that is built onto the image sensor. For a _"full spectrum"_ conversion quartz or a long-pass filter with cut-in at 280 nm is used as replacement. This type of conversion involves disassembling the camera but is rather simple, and costs between 200 € and 500 € depending on the camera model and who does the conversion. The inherent sensitivity of image sensors is lower in the UV than in VIS, but at the NIR end it remains high up to 800 nm or longer. 

In a _"full spectrum"_ conversion, the sensor itself in not modified, and the RGB filters remain on the sensors pixels. Several companies, both is the USA and in Europe offer conversions, but not all are equally reliable. The conversion of a colour camera into a monochrome camera is much more difficult and exists a risk of damaging the sensor making it unusable, as it involves the removal filters that are part of the sensor. Very few companies do this type of conversion, charging from 1200 € to > 1500 €, usually only accepting for conversion specific models or brands of cameras. Removing the filters enhances light sensitivity and image effective resolution. A full _"full spectrum monochrome"_ conversion is also possible.

::: callout-note
### False colour in UV-A and NIR

In a full-spectrum-converted camera the RGB filters on the sensor array remain. These filters also differ in their transmittance for wavelengths in the UV-A and NIR regions, thus, in UV-A and NIR the RGB channels in the sensor respond differently to different wavelengths, even in the absence of red, green and blue light. When the data are "interpreted" by the software (raw converter) as for visible light a false-colour image results. Depending on the case the false colour can be informative or a nuisance. If found a nuisance or confusing the image can be converted from _colour_ into _greyscale_ based on the three channels or by extracting the data for an individual channel. 


:::

A camera converted to "full-spectrum" is sensitive to an extended range of wavelengths of approximately 340 nm to 1000 nm. This range can be constrained by means of optical filters attached either in front or behind the lens. Thus, a "full-spectrum" converted camera can be used for UV-A, VIS or NIR photography by swapping filters. Having a camera sensitive to a wider range of wavelengths is only one requirement, an objective (= lens) that transmits and performs well in the UV and NIR regions is also needed.

### Spectral and hyperspectral cameras

## Objectives

For an objective to be suitable for UV or NIR photography it has to have reasonably high transmittance of the wavelengths we intend to capture in the image and it has be _corrected_ for image aberrations and other problems at these same wavelengths. There exist very few camera objectives that can transmit and are corrected for UV, and those that exist are extremely expensive ($> 10,000$ €) and fragile. I will not discuss such objectives further, instead, I will discuss the cheaper alternative of using normal objectives. Three main difficulties are usually encountered when attempting: low transmittance, ghosting and other reflections, and aberrations than decrease image resolution.   

-  Most photography objectives have high transmittance in the NIR region. Incontrast, most modern, and many vintage, objectives have very low transmittance in the UV region. The reason for this is in the glass used, its thickness, the cemment used to assemble lens groups and the properties of the antireflection coatings used. A general "wisdom" not free of exceptions is that the more elements (more surfaces with coatings) and the thicker these glass elements are, the less likely an objective is to have good UV transmission. This usually means that simpler designs and slower (smaller maximum apperture) objective are more _likely_ to transmit some UV-A radiation. Older or "vintage" objectives had simpler designs and less effective coatings and as a result very few modern objectives have high UV-A transmittance, and the exceptions are a few cheap modern objectives. In general, accidental UV objectives are "prime lenses" (fixed-focal-length objectives) not zooms or extreme wide-angle. It is usual to describe objectives that are not designed for use in UV, but happen to work reasonably well as _"accidental" UV-capable objectives_.

- To prevent reflections non-glass surfaces of the "barrel" of the objective and the edges of glass (or plastic) optical elements are painted or treated black. The shape of the surfaces inside the objective in most cases are also designed to reduce reflections. Coatings that have very high absorptance in the VIS region not necessarily have the same property outside the VIS region. One rather extreme case is black-annodized aluminium which is highly reflective in the NIR region. Many photography lenses produce images with _hot spots_ (usually the center of the image) when used in NIR. In most cases this problem is more noticeable at specific appertures. Frequently, ghosting caused by specular reflections is visible in images as bright spots with the shape of the diaphrogm apperture (opening or "hole"). Flare, caused by scattered radiation or diffuse reflection results is a lowering of image contrast. Although there are many more objectives suitable for NIR photography than for UV-A photography, it is important to keep in mind that some objectives produce better images than others.

- Chromatic aberrations appear when the path of light of different wavelengths through a lens differs. For example, when a white object is photographed, the red, green and blue components can be slighly displace from each other when projected on the sensor or film. In digital photographs chromatic aberretation are visible in high contrast edges as coloured halos. Most photography objectives are corrected for these aberrations by design only in the VIS range, outside this range how objectives behave is an "accident". Given the nature of the aberrations the narrower the range of wavelengths captured, the less likely it is they will affect an image.

The design of any objective is a compromise among multiple criteria, related not only to image quality, but also usability, size, weight and cost of manufacture. The design of different objectives is based on a different compromise. In spite of this, some objectives happen to work reasonably well outside the range of wavelengths for which their design was optimized. They never match the performance of objectives designed for UV photography, which can the used all the way to 250 nm or even shorter wavelengths. However, these extremely expensive and fragile are overkill when the sensitivity of the sensor of a camera is only sensitive to $\lambda > 330\ldots350$ nm.

Finding a good accidental UV objective is made easier by lists published on the internet. Similar lists exist for objectives that do not free of hot-spot problems. These lists are in many cases bases on tests using different criteria and methods. They serve only as an indication, but provide no guarantee. In addition, many now vintage lenses were manufactured during several decades, with occasional changes in antireflection coatings or other alterations that can affect UV transmittance. There are also a couple of modern objects, manufactured until recently, that do trnsmit UV-A1 and even support autofocus in UV (when there is strong light).

In the case of hot spots under NIR, the assessments on which the lists are based are even more subjective as they are usually based on visual assessment of images. In the case of NIR many modern as well as old objectives can be used at least at some appertures. When using vintage objectives on modern cameras one needs to rely on adapter rings, and when using non-macro objectives for macro photography, extenssion tubes are inserted between the objective and the camera. Quite frequenty one can find statements that such tubes without any glass cannot degrade objective performance. This is far from true, and frequently a problem, especially for NIR photography. Many cheap adapters and extenssion tubes are made of aluminium blacked by anodization and are internally highly reflective to NIR radiation and less so to VIS light, but enough to degrade the quality of images not only in NIR. It is common that the inside is ribbed perpendiculalry to the axis of the objective. This helps reduce especular reflections, and when combined with a non-reflecting black paint, very effective. If the ribbed surface is reflective, light is scattered and glare affects the image. These are not the only problems low quality adapters and tubes can introduce. If the dimensions of the mounts and especially the length of adapters is wrong, focusing at infinity can become impossible. This effect is most noticeable with wide angle objectives, e.g., for a fisheye objective with a focal length of 4.5 mm, the required accuracy in the adapter is a small fraction of a millimetre. It is important to be aware of these possible problems. It is also possible to paint the interior wall of extension tubes and adapter oneself if the manufacturer has not done so. The choice of paint is important as only some special paints absorb 95% or more of NIR. 

## Optical filters

Optical filters select wavelengths through absortion and/or through reflection. Each type has its limitations and benefits, both in performance and cost. 

Absorptive glass filters are based on "ionic" glass, i.e., glasses including different ions in their composition. Some of the ions tradditionaly used are metals like iron, lead, copper and chrome. As with any material absorbing photons, fluorescence is one of the possible energy dissipation mechanisms. Thus, some of these filters, e.g., when illuminated with UV-A radiation emit fluorescence in the visible range, and other emit NIR fluorescence when illuminated with blue light. The absorptance depends on their thickness as the glass as a whole has uniform properties across its depth. The change in the absorptance spectrum with the angle of light incidence is moderate. Their cut-offs and cut-ins are gradual, and they exist as band-pass, short-pass and long-pass filters. From the perspective of their use, as the transmitted bands are broad, the distinction between short-pass and band-pass gets blured, i.e., most UV-A and UV-B "short-pass" filters do block UV-C and/or shorter wavelengths.

::: callout-tip
### Filters can deteriorate

Some types of ionic glass filters have high concentrations of metal salts in their composition and their surface can "corrode" in contact with humid air. If they have antireflection, or other coatings or thin layers deposited on their surface they tend be well protected. Those, with no coatings, can need especially in wet climates to be polished using fime cerium oxide paste or restored chemically. The recommendation is to store filters in a dry place and to regularly inspect the condition of their surface.

The spectral transmittance of both clear plastic and glass can change on exposure to strong light, specially blue and shorter wavelengths. In the case of plastics, not only cellulose acetate is affected. Of glasses, those containing iron, usually as an impurity, are the most prone to "yellowing" through "solarization".

:::

Plastic filters are sometimes used, specially at large sizes like $50 \times 50$ mm squares, as they are cheaper. They can be easily damaged in ways that can affect the quality of images, and need to be handled carefully. On the other, small scratches are irrelevant when filters are used on light sources, but it is necessary to protect them from excessive heat.

Until approximately 50 years ago gelatine filters were common. Obviously a thin layer of dry coloured gelatine is extremely fragile, but because they are so thin affect an optical system much less than thicker filters. They are still used, especially for filters located between the back of a lens and the sensor or film. When a thicker glass filter is located between sensor or film and objective, the focus point shifts, in extreme cases restricting the focusing range of the objective.

There is an additional type of absorptive filters, formely very common in photography: a thin light-absorbing layer of coloured gelatine encased between two layers of optical glass. As far as I know, only [Tiffen](https://tiffen.com) still makes this type of filter. 

Interference filters work by reflection from surface multilayer thin coatings. As with reflection in general, reflectance by the thin layers is affected by the light incidence angle. In this type of filters the cut-off and cut-in wavelengths shift significantly at shallow light incidence angles compared to normal incidence. Their main advantage is that they can be designed to have very sharp cut-ind and cut-offs, can have multiple discontinuous trtansmission bands and very strong blocking of off-band radiation. They are available with transmitted bands as narrow as a couple of nm to 100's of nanometres. However´, only the best and most expensive interference filters achieve such high performance. The better filters have more thin-layers with more accurate thickness, which increases the fabrication cost. As they are usually deposited on optical-grade quartz as subtrate, the thikness of the substrate of these filters has little if any affect on their spectral properties. The thin films are fragile, so some of these filters have a hard-coating added at their surface for protection. In spite of working by reflection, which face of the filter points to the light source does not significantly affect their spectral transmittance.

Some of the best VIS-blocking UV-pass filters for photography and astronomy ("Venus filters") are interference filters with VIS-absorbing ionic glass as substrate. Some of them, even have different interference filters deposited on each of their faces. Some photographers argue that which face of these filters faces the sensor can affect reflections within the camera resulting slightly different amounts of glare. Of the common filters used in VIS photography, only some UV-blocking and all UV + NIR blocking filters are interference filters, most other filters are absprptive.

Each glass-air interface reflects approximately 4.5% of the light traversing it as result of the difference in refractive index ($n$). Modern lenses and good photographic filters are anti-reflection multicoated, and the best ones reflect $< 0.1\%$ of the light impinging on their surface. These coatings are similar in principle to interference filters, they change $n$ at the surface. However, thet are designed to minimize reflections across a given range of wavelengths instead of increeasing them. In recent year a further additional coating applied to outer lens surfaces and filters, a fluorine compound coating that alters surface properties so that water runs off the surface and dirt does not stick. Antireflection coating do modify the spectral transmittance, increasing it in the target range of wavelengths but frequently decreasing it in other regions of the spectrum. 

## UV, VIS and NIR radiation sources

Daylight is a strong source of UV-A radiation when the elevation of the sun is more than 30 or 40 degrees above the horizon. The irradiance of NIR compared to VIS in daylight varies less than that of UV. As described in Chapter XX, the scattering of sunlight in the atmosphere is more at shorter than at longer wavelengths. Lanscapes look very different in a UV and in a NIR image. The proportion of UV-A in the shade can be rather high but the low irradiance makes very long exposures necessary.

Xenon flash lamps emit as much or more UV-A radiation than VIS light, but those sold for photography are in most cases filtered so as to block all UV to make their use safer and to avoid a blue cast in photographs. As Xenon flash lamps emit across the whole UV-A, UV-B and UV-C region (although filter for protection), similarly to sunlight, produce false-colour UV images.

LEDs with peaks of emission between 365 nm and 415 nm do emit UV-A and are cheap and readily available. However, because of their rather narrow peaks of emission create nearly monochromatic images, with little false colour. One possibility is to use and array with a mix of LEDs emitting at different but partly overlapping wavelengths.

In the case of NIR all three sources are effective: sunlight, Xenon flash and LEDs. LEDs with their narrow peaks of emission unless combined, fail to produce strong false colour effects.

## Procedures

