---
title: "Introduction"
subtitle: "Research in Plant Photobiology"
date: 2024-03-26
date-modified: today
draft: true
---

## Research on plant responses to ultraviolet radiation (2012) {#sec-intro-plants-UV-2012}

Plants are exposed to ultraviolet (UV) radiation in their natural habitats. The amount and quality of radiation they are exposed to depends on the time of the year, the latitude, the elevation, position in the canopy, clouds and aerosols, and for aquatic plants the depth, solutes and particles contained in the water [see #sec-solar-radiation and #sec-UV-aquatic]. Ultraviolet radiation is consequently a carrier of information about the environment of plants. However, when exposed to enhanced doses of radiation or radiation of short wavelengths, plants can be damaged. When exposed to small doses of radiation plants respond by a mechanism involving the perception of the radiation through a photoreceptor called UVR8 [@Jenkins2009b; @Rizzini2011; @Wu2011; @Christie2012; @DiWu2012; @Heijde2012]. This protein behaves as a pigment at the top of a transduction chain that regulates gene expression. Several genes have been identified as regulated by radiation perceived through UVR8. Some are related to the metabolism of phenolic compounds and are involved in the accumulation of these metabolites.[^1] However, these are not the only genes regulated by UVR8. Genes related to hormone metabolism are also affected, and this could be one of the mechanisms for photomorphogenesis by radiation, for example an increase in leaf thickness or reduction in height of plants. Morphological effects of mediated by UVR8 have been described [@Wargent2009b].

The irradiance of in sunlight is larger than the irradiance of and plants also have photoreceptors that absorb both radiation and blue light. The best studied of these photoreceptors are cryptochromes and phototropins. Cryptochromes are involved in many photomorphogenic responses, including the accumulation of pigments. Phototropins are well known for their role in plant movements such as stomatal opening in blue light and the movement of chloroplasts [see @Christie2007; @Shimazaki2007; @Moeglich2010 for recent reviews].

The balance between the different wavebands, , and (photosynthetically active radiation, 400--700 nm), has a big influence on the effect of radiation on plants. Unrealistically low levels of radiation and enhance the effects of [e.g. @Caldwell1994c]. One reason for this is that radiation is required for photoreactivation, the repair of DNA damage in the light.

From the 1970's until the 1990's the main interest in research on the effects of on plants and other organisms was generated by the increase in ambient exposure caused by ozone depletion in the stratosphere [e.g., @Caldwell1971; @Caldwell1989; @Tevini1993; @Caldwell1994b]. This led to many studies on the effects of increased radiation, both outdoors, in greenhouses and in controlled environments. Frequently the results obtained in outdoor experiments differed from those obtained indoors. This lead to the realization that it is important to use realistic experimental conditions with respect to radiation and its ratio compared to other bands of the solar spectrum. Interactions of responses to radiation with other environmental factors like availability of mineral nutrients, water and temperature, were also uncovered. Effects on terrestrial and aquatic ecosystems of ozone depletion, and the concomitant increase in radiation, have been periodically reviewed in @UNEP2011 [and earlier reports]. These reports include chapters on terrestrial ecosystems [@Ballare2011] and aquatic ecosystems [@Hader2011].

From the 1990's onwards, the interest in the study of the effects of normal (i.e., without stratospheric ozone depletion), as opposed to enhanced radiation increased markedly [e.g., @Paul2001; @Aphalo2003; @Jansen2012]. This was in part due to the realization that even low exposures elicit plant responses, and that these are important for the acclimation of plants to their normal growth environment. Furthermore, as these effects were characterized, interest developed in their possible applications in agriculture and especially horticulture [e.g., @Paul2005].

A further subject of current interest is the enhanced release of greenhouse gases from green and dead biomass caused by action of radiation on pectins [e.g., @Messenger2009; @Bloom2010]. Another long-standing subject of research are the direct and indirect effects of solar radiation on litter decomposition [e.g., @Newsham1997a; @Newsham2001; @Austin2010].

To be able to obtain reliable results from experiments on the effects of radiation on plants, there are many different problems that need to be addressed. This requires background knowledge of both photobiology, radiation physics, and climatology.

## Progress in research and new perspective (2024) {#sec-intro-plants-UV-2024}

In addition to the role of blue light in the photorepair of DNA damage mentioned above, blue light is now known to play additional roles in UV tolerance through the activation of photoreceptors. Molecular studies have revealed a very complex signalling network downstream of plant photoreceptors, that create crosstalk leading complex interactions among the responses to different wavelengths. Time and timing plays a more important role in responses to UV radiation than what was thought 12 years. Nowadays, more emphasis is put on the role of UV radiation as a regulator of plants' structure and function than as a cause damage to plants, but which effect predominates is dose, timing and genotype dependent. Our perspective has changed in several respects as summarised below.

Individual photoreceptors can have multiple modes of action [@Casal1998; @Podolec2021] and the activity of one photorepector may down regulate, up regulate or inhibit the perception of cues by a different photoreceptor [@Casal2009; @Zhao2023]. Responses to UV radiation depend on the current and past spectrum and irradiance of visible and near infrared radiation that plants are exposed to [@Yan2020; @Rai2021]. UVR8 and cryptochrome photoreceptors reciprocally modulate their activity at the signalling level through COP1 and BES mediated interactions [@Rai2019; @Rai2020; @Tissot2020; @Podolec2021]. Further downstream, HY5 and PIFs mediated signalling depends on these two photoreceptors but also on the phytochromes [@Sellaro202x] and phototropins [@Vandenbussche2014]. A recent proposal is that the multiple roles played by photoreceptors sharing signalling network components are made possible by compartimentalization into distinct tissues and cell-types [@Depaepe2023]. 

Furthermore, CRYs and PHYs, control responses affecting optical properties and display of leaves, that could modify the sensitivity to UV radiation by attenuating it or reducing its interception [@Rai2021]. The optical properties of the epidermis vary during the course of the day and in response to exposure to blue light and UV radiation [@Barnes2015a] and also seasonally [@Solanki2019]. Even changes in optical properties of single stranded DNA in chloroplasts can affect sensitivity to damage by UV-B exposure [@SaeidNia2023]. Thus, current understanding of plant responses to UV, VIS and NIR radiation indicates that a broader perspective is needed in the study of plants' responses sunlight and shadelight at multiple time scales [@Barnes2017; @Barnes2018; @Robson2019].

In sunlight, because of the shape of the solar spectrum, UVR8 "the UV-B photoreceptor" mediates responses to both UV-B and UV-A2 radiation, while CRYs are more responsive to solar blue light than to UV-A1 radiation [@Rai2021]. That responses to UV-A1 and UV-A2 radiation are mediated by different photoreceptors and very distinct, introduces the need to differentiate between UV-A1 and UV-A2 in controlled environments [@Rai2021]. In the case of some responses UVR8- and CRY-dependent responses complement each other, and a strong phenotype is observed only when both photoreceptors are inactive [@Rai2020; @Tissot2020].

Both selection and acclimation are crucial to fitness of wild plants and yield of crops [@Aphalo2022]. Acclimation implies that the previously experienced environment affects later responses, and this is not constrained to the same cue or variable, as environmental correlations in the natural environment are exploited by plants and other organisms as sources of information [@Aphalo2022]. Thus, time is important with respect to the developmental stage and previous "experience" (a life-time memory) [@Rai2019] and, in some cases at least, previous generations' "experience" (maternal effects) [@Yan2020].

Acclimation of stomatal responses in response to exposure to UV radiation [@Ac2024] and of photosynthesis to high versus low light levels [@Brelsford2018], can be relevant to drought tolerance [@Jansen2021; @Aphalo2022] and also involves the participation of photoreceptors, sensing UV radiation. In the case of stomata, acclimation can involve chnages in opening speed as well as in relative sensitivity to radiation of different wavelengths [@Aasamaa2017].

The importance of photoperiodism in some plants' responses has been recognised for a long time. However, recent progress has shown that not only photoperiodic, stomatal and photosynthesis responses but also photomorphogenic responses depend on the time of day [@Sellaro202x]. The daily time course of UVR8 dimerization state [@Liao2020] and the seasonality of responses mediated by UVR8 are also two important aspects of timing [@Coffey2018].

Temporal (from seasonal to milliseconds) and spatial heterogeinity in the light environment of plants are an ever present feature outdoors [@Hartikainen2020; @Kotilainen2020; @Durand2023]. Furthermore, even if in its infancy, the study of responses to pulsed light has shown that photoreceptor-dependent responses are not proportional to the average light conditions during the photoperiod, but instead, temporal integration of cues is far more complex and can involve multiple photoreceptors, including UVR8, and PHYs [@Sellaro202x].

_Something about applications in horticulture could be added here._

To study plant responses to UV radiation, consideration of the whole daylight spectrum as well as of the life history of the plants is necessary. It is also necessary to keep in mind relevance to agriculture [@Sadras2021], biological resilience [@Thorogood2023] and the [UN Sustainable Development Goals](https://sdgs.un.org/goals). 

Twelve years ago, it was already recognised that the balance between UV-B radiation and longer wavelengths and the timing of UV-B exposure at noon were needed for relevance of research to plants growing in sunlight. Research in the last 12 years has revealed a very complex molecular signalling mechanism, making it important also for mechanistic studies in controlled environments to be aware of VIS and NIR radiation and the corresponding photoreceptors. This is reflected in that several currently active research groups have already bridged the artificial divide between UV plant photobiology and the rest of plant photobiology.

## Scope of this second edition {#sec-intro-scope}

Because of this new understanding of plants' responses to UV radiation, methods currently important for research on ultraviolet radiation, encompass many methods that are also important for research on visible and near infrared radiation. Thus, for this second edition, we have broadened the scope of the handbook to include a wider range of wavelengths ($280-900\,\mathrm{nm}$) and changed the title. We have however, avoided overlap with other existing publications by excluding, at least initially, methods for the measurement of photosynthesis or plant growth and chemical/biochemical methods used at the laboratory bench.

