---
author:
  - name: Pedro J. Aphalo
    orcid: 0000-0003-3385-972X
    email: pedro.aphalo@helsinki.fi
    affiliation: University of Helsinki
  - name: Wolfgang Bilger
    orcid: 0000-0001-7800-4210
    affiliation: Christian-Albrechts-Universität zu Kiel
  - name: Marcel A. K. Jansen
    orcid: 0000-0003-2014-5859
    affiliation: University College Cork
  - name: Eva Rosenqvist
    orcid: 0000-0001-9288-6248
    affiliation: University of Copenhagen
date: 2024-07-14
date-modified: today
---

# Preface to the 2nd edition {.unnumbered}

{{< lipsum 1-2 >}}

## Plan for the 2nd edition {.unnumbered}

::: callout-note
This is a book created using the "Quarto book" system (version 1.5). To learn more about Quarto books visit <https://quarto.org/docs/books>.
:::

The first edition was published as an outcome of the COST Action: UV4Growth. After the end of the Action, the UV4Plants Association was formed. This second edition is being produced under the auspices of the [UV4Plants Association](https://www.uv4plants.org/).

This new edition will be made available on-line as work in progress, i.e., written in the open.

The text and illustrations from the first edition are being updated to the current state of the science and the methods used in research. In addition, text and illustrations from articles published in the UV4Plants Bulletin are being updated and adapted for inclusion in the new edition.

The structure of the book is not yet final. We are following a plan, but as long chapters are unsuitable for on-line reading, some of the originally planned chapters below have been further divided. In this draft version, chapters have been tentatively grouped into parts.

**The _currently_ planned chapters are:**

* Basics
    1. Introduction
    2. Radiation
    3. Optics
    4. The UV, VIS and NIR environment of terrestrial plants
    5. The UV, VIS and NIR environment of aquatic plants
* Measurements
    6.  Quantifying UV, VIS and NIR radiation
    7.  Measurement of optical properties of leaves
    8.  Quantifying plants' responses 
    9.  Imaging in UV, VIS and short IR radiation
* Design and planning
    10.  Design, planning and data analysis from photobiological experiments
    11.  Ensuring reproducibility
* Realization and treatments
    12.  Manipulating UV and VIS radiation
    13.  Cultivation of terrestrial plants for UV and other photobiological experiments
    14.  Cultivation of aquatic plants for UV and other photobiological experiments
